import { openDB, type DBSchema, type IDBPDatabase } from 'idb'
import { DB_NAME, DB_VERSION, DB_STORE, CUSTOM_SUBJECTS_STORE } from './constants'
import type { CustomSubjectRecord, HistoryEntry, NewHistoryEntry, SubjectData } from '../types'

interface QuizDB extends DBSchema {
  quiz_history: {
    key: number
    value: HistoryEntry
    indexes: { by_slug: string; by_date: string }
  }
  custom_subjects: {
    key: string
    value: CustomSubjectRecord
  }
}

let dbPromise: Promise<IDBPDatabase<QuizDB>> | null = null

function getDB(): Promise<IDBPDatabase<QuizDB>> {
  if (!dbPromise) {
    dbPromise = openDB<QuizDB>(DB_NAME, DB_VERSION, {
      upgrade(db) {
        if (!db.objectStoreNames.contains(DB_STORE)) {
          const store = db.createObjectStore(DB_STORE, {
            keyPath: 'id',
            autoIncrement: true,
          })
          store.createIndex('by_slug', 'slug')
          store.createIndex('by_date', 'dateTaken')
        }
        if (!db.objectStoreNames.contains(CUSTOM_SUBJECTS_STORE)) {
          db.createObjectStore(CUSTOM_SUBJECTS_STORE, { keyPath: 'slug' })
        }
      },
    })
  }
  return dbPromise
}

function byDateDesc(a: HistoryEntry, b: HistoryEntry): number {
  return new Date(b.dateTaken).getTime() - new Date(a.dateTaken).getTime()
}

// ─── Quiz History ──────────────────────────────────────────────────────────

/** Persists a finished attempt; resolves to the stored entry (null on failure). */
export async function saveQuizResult(result: NewHistoryEntry): Promise<HistoryEntry | null> {
  try {
    const db = await getDB()
    const dateTaken = new Date().toISOString()
    // `id` is generated by the autoIncrement key path
    const id = await db.add(DB_STORE, { ...result, dateTaken } as HistoryEntry)
    return { ...result, id, dateTaken }
  } catch (err) {
    console.warn('IndexedDB: failed to save quiz result', err)
    return null
  }
}

export async function getAllHistory(): Promise<HistoryEntry[]> {
  try {
    const db = await getDB()
    const all = await db.getAll(DB_STORE)
    return all.sort(byDateDesc)
  } catch (err) {
    console.warn('IndexedDB: failed to read history', err)
    return []
  }
}

export async function getHistoryBySlug(slug: string): Promise<HistoryEntry[]> {
  try {
    const db = await getDB()
    const index = db.transaction(DB_STORE).store.index('by_slug')
    const entries = await index.getAll(slug)
    return entries.sort(byDateDesc)
  } catch (err) {
    console.warn('IndexedDB: failed to read history by slug', err)
    return []
  }
}

export async function deleteHistoryEntry(id: number): Promise<void> {
  try {
    const db = await getDB()
    await db.delete(DB_STORE, id)
  } catch (err) {
    console.warn('IndexedDB: failed to delete history entry', err)
  }
}

export async function clearAllHistory(): Promise<void> {
  try {
    const db = await getDB()
    await db.clear(DB_STORE)
  } catch (err) {
    console.warn('IndexedDB: failed to clear history', err)
  }
}

// ─── Custom Subjects ───────────────────────────────────────────────────────

export async function saveCustomSubject(subjectData: SubjectData): Promise<void> {
  const db = await getDB()
  await db.put(CUSTOM_SUBJECTS_STORE, {
    ...subjectData,
    isCustom: true,
    addedAt: new Date().toISOString(),
  })
}

export async function getAllCustomSubjects(): Promise<CustomSubjectRecord[]> {
  try {
    const db = await getDB()
    return await db.getAll(CUSTOM_SUBJECTS_STORE)
  } catch (err) {
    console.warn('IndexedDB: failed to load custom subjects', err)
    return []
  }
}

export async function deleteCustomSubject(slug: string): Promise<void> {
  try {
    const db = await getDB()
    await db.delete(CUSTOM_SUBJECTS_STORE, slug)
  } catch (err) {
    console.warn('IndexedDB: failed to delete custom subject', err)
  }
}

export async function getCustomSubjectSlugs(): Promise<Set<string>> {
  try {
    const db = await getDB()
    const all = await db.getAllKeys(CUSTOM_SUBJECTS_STORE)
    return new Set(all)
  } catch {
    return new Set()
  }
}
